name: kkobulang
description: 꼬불랑 - 한국 곱슬머리 관리 & 커뮤니티 앱

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  google_generative_ai: ^0.4.6
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/kkobulang_logo.png
    - assets/kkobulang_sun.png
    - assets/kkobulang_green.png
    - assets/f2a.png
    - assets/f2b.png
    - assets/f2c.png
    - assets/f3a.png
    - assets/f3b.png
    - assets/f3c.png
    - assets/f4a.png
    - assets/f4b.png
    - assets/f4c.png
    - assets/m2a.png
    - assets/m2b.png
    - assets/m2c.png
    - assets/m3a.png
    - assets/m3b.png
    - assets/m3c.png
    - assets/m4a.png
    - assets/m4b.png
    - assets/m4c.png
